
name: Update Language Statistics

on:
  workflow_dispatch:

  schedule:
    - cron: "0 3 * * *"

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Generate language statistics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: steiciealeixosousa
        run: npm start

      - name: Commit SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Update language statistics"
          file_pattern: assets/languages.svg
